### ISSUE TITLE
Error could not load kernel32.dll, status c0000135

### ISSUE THREAD

**Issue by teldom14** [Fcharan/Wine-Hangover-Patched#1]
After run hangover, could not load kernel32.dll, status c0000135

**Comment by Fcharan** [comment]
When Did You Install Because I Updated The Script Again

**Comment by teldom14** [comment]
> When Did You Install Because I Updated The Script Again

I just tried to reinstall, the error persisted. origin os 5 android 15

**Comment by Fcharan** [comment]
This can also be a android version 15 because removing of 32 bit completely

**Comment by IMTHECOOLEST** [comment]
I'm on android 10 and I get this aswell

**Comment by Fcharan** [comment]
Try Again Now

**Comment by ifoodplayer** [comment]
I'm on Android 12.1 with a snadragon 450 and I'm also having this same problem

**Comment by Fcharan** [comment]
Please Give Me Some Time I'll Update And Inform Back

**Comment by 132edsaz** [comment]
Yes bro I can wait up to a week if you want I also wanted to tell you that I have a unisoc 👍

**Comment by 132edsaz** [comment]
Yes bro I can wait up to a week if you want I also wanted to tell you that I have a unisoc 👍

**Comment by SkeletonDan1057** [comment]
Hey bro, i have a Samsung Galaxy a02s With a Snapdragon 450, I tried a few things and managed to solve this problem

**Comment by SkeletonDan1057** [comment]
After installing Wine Hangover, type "pkg install wine-stable winetricks" as written. This should solve the kernel32.dll problem.

**Comment by SkeletonDan1057** [comment]
Fcharan, can you help me with something? Games/programs/3dtests apps don't open, they just close

**Comment by SkeletonDan1057** [comment]
And when I try to enter the 3d test manually, like typing "wine <nameof3dtestapp.exe>" it gives an error described as: wine: could not load <partition/windows/syswow64/ntdll.dll

**Comment by 132edsaz** [comment]
> After installing Wine Hangover, type "pkg install wine-stable winetricks" as written. This should solve the kernel32.dll problem.

It doesn't work, I still have a black screen and the same error

**Comment by SkeletonDan1057** [comment]
The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135

**Comment by SkeletonDan1057** [comment]
If you get an error, try removing the part that says "sudo", leaving only the clean command, without using the super user.

**Comment by 132edsaz** [comment]
> The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135

Don't worry, I'm Spanish but I may not have the sudo command):

**Comment by 132edsaz** [comment]
> The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135

Don't worry, I'm Spanish but I may not have the sudo command):

**Comment by SkeletonDan1057** [comment]
> > The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135
> 
> Don't worry, I'm Spanish but I may not have the sudo command):

Did you manage to solve it?

**Comment by 132edsaz** [comment]
> > > The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135
> > 
> > Don't worry, I'm Spanish but I may not have the sudo command):
> 
> Did you manage to solve it?

I can't yet, I'm trying everything xD

**Comment by 132edsaz** [comment]
> > > The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135
> > 
> > Don't worry, I'm Spanish but I may not have the sudo command):
> 
> Did you manage to solve it?

I can't yet, I'm trying everything xD

**Comment by ifoodplayer** [comment]
> > > > The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135
> > > 
> > > 
> > > Don't worry, I'm Spanish but I may not have the sudo command):
> > 
> > 
> > Did you manage to solve it?
> 
> I can't yet, I'm trying everything xD

It worked! The kernel32.dll error is gone, just type

winetricks dlls list
and then
winetricks dlls install kernel32 and start the wine hangover

**Comment by IMTHECOOLEST** [comment]
> > > > > The site must be in ptbr because I'm Brazilian, but try to translate it to English https://www.vivaolinux.com.br/topico/vivaolinux/wine-could-not-load-kernel32dll-status-c0000135
> > > > 
> > > > 
> > > > Don't worry, I'm Spanish but I may not have the sudo command):
> > > 
> > > 
> > > Did you manage to solve it?
> > 
> > 
> > I can't yet, I'm trying everything xD
> 
> It worked! The kernel32.dll error is gone, just type
> 
> winetricks dlls list and then winetricks dlls install kernel32 and start the wine hangover

Didn't work, scam

**Comment by IMTHECOOLEST** [comment]
That f*cked up wine hangover and now cubed3d won't work

**Comment by Crauzer58** [comment]
Heroes come

1. apt install hangover
2. cd $HOME
3. rm -rf .wine
4. ~/wine_hangover/arm64-v8a/bin/wine explorer /desktop=shell explorer

**Comment by IMTHECOOLEST** [comment]
> Heroes come
> 
>     1. apt install hangover
> 
>     2. cd $HOME
> 
>     3. rm -rf .wine
> 
>     4. ~/wine_hangover/arm64-v8a/bin/wine explorer /desktop=shell explorer

Now it gives me an error
